### PR TITLE
made changes to increase snake speed when eating food

### PR DESCRIPTION
**Pull request by sulfur05**
added a line to increase the speed by 0.1 in the gameEngine() function.
@rootCircle please check this pr

### CODE REVIEW

**Comment by rootCircle** [comment]
cc @ANKITy102

**Comment by ANKITy102** [comment]
@sulfur05, reinitialize the speed on collision.

**Comment by sulfur05** [comment]
@ANKITy102 , now the speed reinitializes to 0 on collision

**Comment by sulfur05** [comment]
@ANKITy102, changes have been made to reinitialize the speed to its initial value

**Comment by ANKITy102** [comment]
@sulfur05, Nice. Try from next time to give more elaborative pr with issue id mention in it.

**Pull request closed without merging**
