### PR TITLE
Enhance Mobile Compatibility and Controls #6

### PR DESCRIPTION
**Pull request by 0PrashantYadav0**
Added on screen keys for mobile user or user with screen width less then 1240px.
Also added touch  integrate swipe gestures for intuitive movement on touchscreens.
This PR contains 2 different commit for above features respectively.
I was not able to test it on mobile but i do check all the functionality on my system.
Screenshot 2024-03-15 at 5 45 41 PM

### CODE REVIEW

**Comment by ANKITy102** [comment]
> Added on screen keys for mobile user or user with screen width less then 1240px. Also added touch integrate swipe gestures for intuitive movement on touchscreens. This PR contains 2 different commit for above features respectively. I was not able to test it on mobile but i do check all the functionality on my system. Screenshot 2024-03-15 at 5 45 41 PM

@0PrashantYadav0, Change the text in button with icons of arrows. Keep  left and right arrow on left side of screen. And keep up and down arrow on right side of screen for easy navigation for user.

**Comment by 0PrashantYadav0** [comment]
@ANKITy102 I add all the required thing that you asked for. Please review again.

**Comment by ANKITy102** [comment]
@0PrashantYadav0, Please show the ss of the mobile view.

**Comment by 0PrashantYadav0** [comment]
Screenshot 2024-03-16 at 10 44 04 PM

@ANKITy102 please review

**Comment by ANKITy102** [comment]
@0PrashantYadav0, Good Work. Please issue id in pr from next time.

**Pull request closed without merging**
