### PR TITLE
Added Celebration Pop-up

### PR DESCRIPTION
**Pull request by sulfur05**
Score count and max count now working, for this changes have been made in the gameEngine() function along with initialization of new variables - 'count' and 'maxCount'. If the player beats the high score, a pop-up opens using the openPopUp() function and closes when the 'play again' button is pressed. HTML and CSS has been added for the popup.
@rootCircle please check this pr

### CODE REVIEW

**Comment by rootCircle** [comment]
cc @ANKITy102

**Comment by ANKITy102** [comment]
@sulfur05, Please give video of the feature and tag the issue with issueid. 
Note that popup I mean that some animation should occur like text fade-in and fade-out with text moving up animation.

**Comment by sulfur05** [comment]
improved the pop-up box's animation and also added bouncy text animation
this solves issue #8 
below is link to the video-
https://github.com/iiitl/snake-game-js/assets/146582625/fb10be05-a67e-458e-80ab-62805d535484

**Comment by ANKITy102** [comment]
@sulfur05, Nice!

**Pull request closed without merging**
